FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Install nodemon globally for hot reload
RUN npm install -g nodemon

# Copy the rest of the backend code
COPY . .

EXPOSE 3001

CMD ["npm", "run", "start"]